name: Upload wfc.log from VM

on:
  workflow_dispatch:
    inputs:
      vm_ip:
        description: 'External IP address of the VM'
        required: true
        type: string
      log_path:
        description: 'Full path to the log file on the VM'
        required: true
        type: string

jobs:
  fetch-log-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client netcat

    - name: Test SSH port
      run: |
        echo "🔍 Testing if port 22 is reachable on ${{ inputs.vm_ip }}..."
        nc -zv ${{ inputs.vm_ip }} 22 || {
          echo "❌ Port 22 is not reachable. Is the VM running and exposed?"
          exit 1
        }
