name: Upload wfc.log from VM

on:
  workflow_dispatch:
    inputs:
      vm_ip:
        description: 'External IP address of the VM (not internal/private)'
        required: true
        type: string
      log_path:
        description: 'Full path to the log file on the VM'
        required: true
        type: string

jobs:
  fetch-log-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Print debug info
      run: echo "Connecting to VM at ${{ inputs.vm_ip }}"

    - name: Set up SSH and fetch log
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh

        # Sanitize the SSH key and write it to file
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Add key to ag
